REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "userId";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "userId";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL PRIVILEGES ON SEQUENCES FROM "userId";
