GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "userId";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "userId";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO "userId";